// Comprehensive list of Hyderabad areas and localities
export const HYDERABAD_LOCATIONS = [
  'All',
  // Central Hyderabad
  'Abids',
  'Ameerpet',
  'Asif Nagar',
  'Bahadurpura',
  'Banjara Hills',
  'Basheerbagh',
  'Charminar',
  'Chikkadpally',
  'Domalguda',
  'Gunfoundry',
  'Himayatnagar',
  'Jubilee Hills',
  'Kachiguda',
  'Khairatabad',
  'Koti',
  'Lakdi-ka-pul',
  'Masab Tank',
  'Mehdipatnam',
  'Mozamjahi Market',
  'Narayanguda',
  'Nampally',
  'Panjagutta',
  'Somajiguda',
  'Sultan Bazar',
  'Tarnaka',
  
  // West Hyderabad
  'Gachibowli',
  'Hitech City',
  'Madhapur',
  'Kondapur',
  'Banjara Hills',
  'Jubilee Hills',
  'Film Nagar',
  'Manikonda',
  'Nanakramguda',
  'Kokapet',
  'Narsingi',
  'Raidurg',
  'Serilingampally',
  'TSPA',
  
  // North Hyderabad
  'Alwal',
  'Begumpet',
  'Bollaram',
  'Bowenpally',
  'Cantonment',
  'Compally',
  'Dundigal',
  'Fatehnagar',
  'Hakimpet',
  'Jeedimetla',
  'Kompally',
  'Medchal',
  'Miyapur',
  'Patancheru',
  'Quthbullapur',
  'Secunderabad',
  'Shamshabad',
  'Suchitra',
  'Trimulgherry',
  
  // East Hyderabad
  'Boduppal',
  'Cherlapally',
  'Dilsukhnagar',
  'Ecil',
  'Ghatkesar',
  'Habsiguda',
  'Hayathnagar',
  'Kapra',
  'Kushaiguda',
  'LB Nagar',
  'Malakpet',
  'Malkajgiri',
  'Moula Ali',
  'Nacharam',
  'Nagole',
  'Uppal',
  'Peerzadiguda',
  'Ramanthapur',
  'Saroornagar',
  'Vanasthalipuram',
  'Yapral',
  
  // South Hyderabad
  'Attapur',
  'Bandlaguda',
  'Balapur',
  'Chandrayangutta',
  'Falaknuma',
  'Golconda',
  'Kothapet',
  'Langar Houz',
  'Madannapet',
  'Mallepally',
  'Moosapet',
  'Old City',
  'Pahadi Shareef',
  'Rajendranagar',
  'Santosh Nagar',
  'Shamshabad',
  'Tolichowki',
  'Yakutpura',
  
  // Outer Ring Road Areas
  'Financial District',
  'HITEC City',
  'Gachibowli',
  'Lingampally',
  'Kukatpally',
  'Bachupally',
  'Kollur',
  'Shamshabad Airport',
  'Budvel',
  'Narsingi',
  
  // Other Major Areas
  'Ameenpur',
  'Chandanagar',
  'Hafeezpet',
  'Kukatpally',
  'Nizampet',
  'Pragathi Nagar',
  'KPHB Colony',
  'Moosapet',
  'Balanagar',
  'Erragadda',
  'Sanath Nagar',
  'SR Nagar',
  'Yousufguda',
].sort();
